services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: samsung-review-api
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 10s
    networks:
      - samsung-review-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: samsung-review-frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000/ask
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - samsung-review-network


networks:
  samsung-review-network:
    driver: bridge
    name: samsung-review-network